name: Generate Snake

on:
 
  schedule:
    - cron: "0 0 * * *"
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: sicora-dev
          outputs: dist/snake.svg

      - name: Guardar Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
